### ISSUE TITLE
Which situation?

### ISSUE THREAD

**Issue by M-Mortaz** [maria-j70/wallet#2]
https://github.com/maria-j70/wallet/blob/c13f6690f53f00c1e0309dea9bce743095c4fadd/transaction/models.py#L90

At which situation does this error `IntegrityError` could occur?

**Comment by maria-j70** [comment]
اگه  transaction.atomic کار نکنه. البته همه موقعیت های که فکر میکنم رو هندل کردم اما اگه موقعیت ناشناخته ای پیش بیاد یا موقعیتی که به ذهنم نرسیده

**Comment by M-Mortaz** [comment]
In these type of scenarios,  we must inform about the errors, to resolve them. So at least add logger (file logger in django, which can implement easily). Don't let your codes has bug silently( means you must track them)
